version: '3.8'

services:
  scanner-to-paperless:
    build: .
    container_name: scanner-to-paperless
    environment:
      - PAPERLESS_HOST:${PAPERLESS_HOST}
      - PAPERLESS_API_TOKEN:${PAPERLESS_API_TOKEN}
      - SCANNER_HOST:${SCANNER_HOST}
      - SCANNER_BASIC_AUTH:${SCANNER_BASIC_AUTH}
